apiVersion: v1
kind: Service
metadata:
  name: hazelcast-worker
  labels:
    app: hazelcast-worker
spec:
  type: NodePort
  selector:
    app: hazelcast-worker
  ports:
  - protocol: TCP
    port: 5701
    name: hzport-worker
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hazelcast-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hazelcast-worker
    spec:
      containers:
      - name: hazelcast-node
        image: codeurjc/squirrel-dray-k8s
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 5701
        envFrom:
        - configMapRef:
            name: hz-config-worker
