apiVersion: v1
kind: ConfigMap
metadata:
  name: hz-config-worker
  namespace: default
data:
  NAMESPACE: "default"
  SERVICE_NAME: "hazelcast-worker"
  SERVICE_LABEL_NAME: "cluster01"
  SERVICE_LABEL_VALUE: "true"
  TYPE: "worker"