apiVersion: v1
kind: Service
metadata:
  name: hazelcast-web
  labels:
    app: hazelcast-web
spec:
  type: NodePort
  selector:
    app: hazelcast-web
  ports:
  - protocol: TCP
    port: 5000
    name: hzport-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-web
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hazelcast-web
  replicas: 1
  template:
    metadata:
      labels:
        app: hazelcast-web
    spec:
      containers:
      - name: hazelcast-web
        image: codeurjc/squirrel-dray-k8s
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: hz-config-web
